server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: db_user
    password: db_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: false
    defer-datasource-initialization: true