server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/order
    username: ${DB_USER:db_user}
    password: ${DB_PASSWORD:db_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: false
        jdbc:
          batch_size: 500
        order_inserts: true
    defer-datasource-initialization: true
